## Import relavent libraries

In [1]:
import pandas as pd
import numpy as np

## Load Data

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Values  day of the week  \
0         0         0         0         1             7                1   
1         0         0         0         0             7                1   
2         0         0         0         1             7                2   
3         1         0         0         0             7                3   
4         0         0         0         1             7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## Create targets

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets

In [8]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Values  day of the week  \
0         0         0         0         1             7                1   
1         0         0         0         0             7                1   
2         0         0         0         1             7                2   
3         1         0         0         0             7                3   
4         0         0         0         1             7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## Saving checkpoint

In [9]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Distance to Work', 'Education', 'Daily Work Load Average', 'Month Values'], axis = 1)

In [10]:
data_with_targets

Reason_1  Reason_2  Reason_3  Reason_4  day of the week  \
0           0         0         0         1                1   
1           0         0         0         0                1   
2           0         0         0         1                2   
3           1         0         0         0                3   
4           0         0         0         1                3   
..        ...       ...       ...       ...              ...   
695         1         0         0         0                2   
696         1         0         0         0                2   
697         1         0         0         0                3   
698         0         0         0         1                3   
699         0         0         0         1                3   

     Transportation Expense  Age  Body Mass Index  Children  Pets  \
0                       289   33               30         2     1   
1                       118   50               31         1     0   
2                       179   38               31         0     0   
3                       279   39               24         2     0   
4                       289   33               30         2     1   
..                      ...  ...              ...       ...   ...   
695                     179   40               22         2     0   
696                     225   28               24         1     2   
697                     330   28               25         0     0   
698                     235   32               25         0     0   
699                     291   40               25         1     1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 11 columns]

## Select the inputs for regression

In [11]:
unscaled_inputs = data_with_targets.iloc[:,:10]
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  day of the week  \
0           0         0         0         1                1   
1           0         0         0         0                1   
2           0         0         0         1                2   
3           1         0         0         0                3   
4           0         0         0         1                3   
..        ...       ...       ...       ...              ...   
695         1         0         0         0                2   
696         1         0         0         0                2   
697         1         0         0         0                3   
698         0         0         0         1                3   
699         0         0         0         1                3   

     Transportation Expense  Age  Body Mass Index  Children  Pets  
0                       289   33               30         2     1  
1                       118   50               31         1     0  
2                       179   38               31         0     0  
3                       279   39               24         2     0  
4                       289   33               30         2     1  
..                      ...  ...              ...       ...   ...  
695                     179   40               22         2     0  
696                     225   28               24         1     2  
697                     330   28               25         0     0  
698                     235   32               25         0     0  
699                     291   40               25         1     1  

[700 rows x 10 columns]

## Standardize the data

In [12]:
from sklearn.preprocessing import StandardScaler

absenteeism_scalar = StandardScaler()

In [13]:
absenteeism_scalar.fit(unscaled_inputs)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [14]:
scaled_inputs = absenteeism_scalar.transform(unscaled_inputs)

In [15]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ...,  0.76743118,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ...,  1.00263338,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  1.00263338,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ..., -0.40857982,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.40857982,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.40857982,
        -0.01928035,  0.26848661]])

In [16]:
scaled_inputs.shape

(700, 10)

## Split the data into train and test, and shuffle

## Import relavent libraries

In [17]:
from sklearn.model_selection import train_test_split

## Split

In [18]:
train_test_split(scaled_inputs, targets)

[array([[-0.57735027, -0.09298136, -0.31448545, ...,  0.06182458,
         -0.01928035,  2.8430157 ],
        [-0.57735027, -0.09298136,  3.17979734, ..., -1.11418642,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136,  3.17979734, ..., -0.64378202,
         -0.01928035,  1.12666297],
        ...,
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.40857982,
         -0.91902997, -0.58968976],
        [ 1.73205081, -0.09298136, -0.31448545, ...,  0.29702678,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.40857982,
         -0.01928035,  0.26848661]]),
 array([[-0.57735027, -0.09298136,  3.17979734, ...,  0.76743118,
          0.88046927,  0.26848661],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.40857982,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136,  3.17979734, ...,  1.00263338,
         -0.91902997, -0.58968976],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -

In [19]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size= 0.8, random_state = 30 )

In [20]:
print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

(560, 10) (560,) (140, 10) (140,)


## Logistic Regression with sklearn

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

## Train the model

In [22]:
reg = LogisticRegression()

In [23]:
reg.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [24]:
reg.score(x_train, y_train)

0.7660714285714286

## Check accuracy manually

In [25]:
model_outputs = reg.predict(x_train)

In [26]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False, False, False,  True,  True,  True, False, False,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True, False,

In [27]:
np.sum(model_outputs == y_train)

429

In [28]:
accuracy_manual = np.sum(model_outputs == y_train)/ model_outputs.shape

In [29]:
accuracy_manual

array([0.76607143])

## Finding intercept and coefficients

In [30]:
reg.intercept_

array([-0.18036604])

In [31]:
reg.coef_

array([[ 2.04083495,  0.27981608,  1.54732921,  1.39432249, -0.20398084,
         0.705694  , -0.26648617,  0.26684798,  0.44549281, -0.41136623]])

In [32]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'day of the week',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Children',
       'Pets'], dtype=object)

In [33]:
feature_names = unscaled_inputs.columns.values

In [34]:
summary_table = pd.DataFrame( columns=['feature_names'], data = feature_names)
summary_table['Coefficients'] = np.transpose(reg.coef_)
summary_table

feature_names  Coefficients
0                Reason_1      2.040835
1                Reason_2      0.279816
2                Reason_3      1.547329
3                Reason_4      1.394322
4         day of the week     -0.203981
5  Transportation Expense      0.705694
6                     Age     -0.266486
7         Body Mass Index      0.266848
8                Children      0.445493
9                    Pets     -0.411366

In [35]:
summary_table.index = summary_table.index + 1

In [36]:
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table

feature_names  Coefficients
1                 Reason_1      2.040835
2                 Reason_2      0.279816
3                 Reason_3      1.547329
4                 Reason_4      1.394322
5          day of the week     -0.203981
6   Transportation Expense      0.705694
7                      Age     -0.266486
8          Body Mass Index      0.266848
9                 Children      0.445493
10                    Pets     -0.411366
0                Intercept     -0.180366

In [37]:
summary_table = summary_table.sort_index()
summary_table

feature_names  Coefficients
0                Intercept     -0.180366
1                 Reason_1      2.040835
2                 Reason_2      0.279816
3                 Reason_3      1.547329
4                 Reason_4      1.394322
5          day of the week     -0.203981
6   Transportation Expense      0.705694
7                      Age     -0.266486
8          Body Mass Index      0.266848
9                 Children      0.445493
10                    Pets     -0.411366

## Interpret the coefficients

In [38]:
summary_table['ratios'] = np.exp(summary_table.Coefficients)

In [39]:
summary_table

feature_names  Coefficients    ratios
0                Intercept     -0.180366  0.834965
1                 Reason_1      2.040835  7.697033
2                 Reason_2      0.279816  1.322886
3                 Reason_3      1.547329  4.698904
4                 Reason_4      1.394322  4.032242
5          day of the week     -0.203981  0.815478
6   Transportation Expense      0.705694  2.025252
7                      Age     -0.266486  0.766067
8          Body Mass Index      0.266848  1.305842
9                 Children      0.445493  1.561259
10                    Pets     -0.411366  0.662744

In [40]:
summary_table.sort_values('ratios', ascending = False)

feature_names  Coefficients    ratios
1                 Reason_1      2.040835  7.697033
3                 Reason_3      1.547329  4.698904
4                 Reason_4      1.394322  4.032242
6   Transportation Expense      0.705694  2.025252
9                 Children      0.445493  1.561259
2                 Reason_2      0.279816  1.322886
8          Body Mass Index      0.266848  1.305842
0                Intercept     -0.180366  0.834965
5          day of the week     -0.203981  0.815478
7                      Age     -0.266486  0.766067
10                    Pets     -0.411366  0.662744

## Testing the Model

In [41]:
reg.score(x_test, y_test)

0.8214285714285714

## Save the Model

In [42]:
import pickle

In [43]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [44]:
with open('to_be_scaled', 'wb') as file:
    pickle.dump(unscaled_inputs, file)